### ISSUE TITLE
how does this even fix anything

### ISSUE THREAD

**Issue by dakrk** [melkwastaken/collabvm-fix#4]
all I can see is just broken C# code and other useless stuff, how does this even fix CollabVM at all

**Comment by melkwastaken** [comment]
it applies itself, but we accept collabators so yeah

**Comment by melkwastaken** [comment]
blame myself

**Comment by melkwastaken** [comment]
magic button if u wanna be invited, just added u
https://github.com/melkwastaken/collabvm-fix/invitations
