### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Undefishin** [melkwastaken/collabvm-fix#5]
why does this exist?

**Comment by melkwastaken** [comment]
idk, inspiration also how did u get here

**Comment by melkwastaken** [comment]
oh fuck it, anyways wanna be invited

**Comment by melkwastaken** [comment]
Closed due to no messages since when asked, and locked

**Comment by melkwastaken** [comment]
you may open another issue, but it needs to be valid next time, or the issue would be deleted
